- title: Journal Reviewers
  description: TOSEM 2021;https://dl.acm.org/journal/tosem, SOSYM 2021;https://www.sosym.org/


- title: Program Committee

  description: APR 2023;http://program-repair.org/workshop-2023/, MSR 2023 (Junior PC); https://conf.researchr.org/track/msr-2023/msr-2023-junior-pc?, MSR4SA 2022;https://msr4sa.github.io/msr4sa2022/, MSR 2021 (Shadow PC );https://2021.msrconf.org/track/msr-2021-shadow-pc?, ECOOP 2021 (Artifacts Evaluation Committee);https://2021.ecoop.org/committee/ecoop-2021-ecoop-artifacts-artifact-evaluation-committee, ISSTA 2021 (Artifacts Evaluation Committee);https://conf.researchr.org/track/issta-2021/issta-2021-artifact-evaluation


- title: Subreviewer
  description: ICSE;http://www.icse-conferences.org/, ASE;https://conf.researchr.org/series/ase, ISSTA;https://conf.researchr.org/series/ISSTA, ICSME;https://conf.researchr.org/series/ICSME, QRS;https://ieeexplore.ieee.org/xpl/conhome/1810024/all-proceedings, SAC;https://dl.acm.org/conference/sac, ICPC;https://conf.researchr.org/series/ICPC

